### ISSUE TITLE
Errors With Running The Bot

### ISSUE THREAD

**Issue by lexinnit** [YassienW/kik-node-api#6]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './src/kikClient'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)      
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Liam\Desktop\Kik - StarBot\exampleBot.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)     
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)       
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

would anyone happen to know a fix for this?

**Comment by YassienW** [comment]
Try deleting your node_modules folder and reinstalling the package

**Comment by YassienW** [comment]
Closing due to inactivity
